#!/bin/sh
# Installs Kel's dotfiles on any Unix-like system.

cd `dirname $0` # Move to the directory of the dotfile repository

touch $HOME/.profile && echo "source $(pwd)/profile" >> $HOME/.profile
touch $HOME/.zshrc && echo "source $(pwd)/updater" >> $HOME/.zshrc \
  && echo "source $(pwd)/zshrc" >> $HOME/.zshrc
touch $HOME/.vimrc && echo "source $(pwd)/vimrc" >> $HOME/.vimrc
touch $HOME/.tmux.conf && echo "source-file $(pwd)/tmuxrc" >> $HOME/.tmux.conf
mkdir -p $HOME/.config/awesome 
ln -s awesomerc.lua $HOME/.config/awesome/rc.lua
ln -s awesometheme.lua $HOME/.config/awesome/theme.lua

echo ""
echo "Configs are now sourced by [38;5;011m~/.profile[00m, [38;5;011m~/.zshrc[00m, [38;5;011m~/.vimrc[00m, and [38;5;011m~/.tmux.conf[00m"
echo "  to the files in this directory. Whenever a new shell is opened,"
echo "  the configs within this directory are updated. However, if you"
echo "  move this directory, [38;5;011mbe sure to update your homedir's configs to"
echo "  point to the new location.[00m"
echo ""
echo "[38;5;013mHave a nice day![00m"
echo ""
